# main menu
[[main]]
identifier = "home"
name = "Home"
url = "/"
weight = 1

[[main]]
identifier = "blog"
name = "Blog"
url = "/blog/"
weight = 2


# footer menu
[[footer]]
identifier = "home"
name = "Home"
url = "/"
weight = 1

[[footer]]
identifier = "blog"
name = "Blog"
url = "/blog/"
weight = 2
